### ISSUE TITLE
error handling 0.11.x firmware

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.wled#110]
reminder : https://forum.iobroker.net/topic/29833/wled-led-streifen-ws2812b-ws2811-sk6812-apa102-bedienen/313

```

2020-12-25 19:40:09.073 - info: host.iobroker-deb instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
--
  | 2020-12-25 19:40:39.224 - info: host.iobroker-deb "system.adapter.wled.0" disabled
  | 2020-12-25 19:40:39.225 - info: host.iobroker-deb stopInstance system.adapter.wled.0 (force=false, process=true)
  | 2020-12-25 19:40:39.226 - info: host.iobroker-deb stopInstance system.adapter.wled.0 send kill signal
  | 2020-12-25 19:40:39.229 - info: wled.0 (16106) Got terminate signal TERMINATE_YOURSELF
  | 2020-12-25 19:40:39.236 - info: wled.0 (16106) terminating
  | 2020-12-25 19:40:39.237 - info: wled.0 (16106) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
  | 2020-12-25 19:40:39.237 - info: wled.0 (16106) cleaned everything up...
  | 2020-12-25 19:40:39.783 - info: host.iobroker-deb instance system.adapter.wled.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
  | 2020-12-25 19:41:20.861 - info: host.iobroker-deb "system.adapter.wled.0" enabled
  | 2020-12-25 19:41:20.904 - info: host.iobroker-deb instance system.adapter.wled.0 started with pid 22618
  | 2020-12-25 19:41:22.600 - info: wled.0 (22618) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
  | 2020-12-25 19:41:22.610 - info: wled.0 (22618) starting. Version 0.5.4 in /opt/iobroker/node_modules/iobroker.wled, node: v12.20.0, js-controller: 3.1.6
  | 2020-12-25 19:41:22.637 - info: wled.0 (22618) Try to contact known devices
  | 2020-12-25 19:41:22.638 - info: wled.0 (22618) Try to contact : "Wohnzimmer Schrank" on IP : 192.168.0.193
  | 2020-12-25 19:41:26.399 - info: wled.0 (22618) Device : "Wohnzimmer Schrank" Successfully connected on IP : 192.168.0.193
  | 2020-12-25 19:41:26.404 - info: wled.0 (22618) Bonjour service startet, new devices will be detected automatically :-)
  | 2020-12-25 19:41:26.405 - info: wled.0 (22618) WLED initialisation finalized, ready to do my job have fun !
  | 2020-12-25 19:42:59.247 - info: wled.0 (22618) New WLED device found wled-5d9de3 on IP 192.168.0.192
  | 2020-12-25 19:43:00.458 - info: wled.0 (22618) [Error catched and send to Sentry, thank you collaborating!] error: State attribute definition missing for + u
  | 2020-12-25 19:43:00.459 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
  | 2020-12-25 19:43:00.459 - error: wled.0 (22618) unhandled promise rejection: Cannot read property 'captureException' of undefined
  | 2020-12-25 19:43:00.460 - error: wled.0 (22618) TypeError: Cannot read property 'captureException' of undefined
  | at Wled.sendSentry (/opt/iobroker/node_modules/iobroker.wled/main.js:802:37)
  | at Wled.create_state (/opt/iobroker/node_modules/iobroker.wled/main.js:698:11)
  | at Wled.readData (/opt/iobroker/node_modules/iobroker.wled/main.js:426:18)
  | at runMicrotasks ()
  | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | 2020-12-25 19:43:00.461 - info: wled.0 (22618) cleaned everything up...
  | 2020-12-25 19:43:00.477 - info: wled.0 (22618) [Error catched and send to Sentry, thank you collaborating!] error: State attribute definition missing for + t
  | 2020-12-25 19:43:00.478 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
  | 2020-12-25 19:43:00.478 - error: wled.0 (22618) unhandled promise rejection: Cannot read property 'captureException' of undefined
  | 2020-12-25 19:43:00.478 - error: wled.0 (22618) TypeError: Cannot read property 'captureException' of undefined
  | at Wled.sendSentry (/opt/iobroker/node_modules/iobroker.wled/main.js:802:37)
  | at Wled.create_state (/opt/iobroker/node_modules/iobroker.wled/main.js:698:11)
  | at Wled.readData (/opt/iobroker/node_modules/iobroker.wled/main.js:426:18)
  | at runMicrotasks ()
  | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | 2020-12-25 19:43:00.479 - info: wled.0 (22618) terminating
  | 2020-12-25 19:43:00.480 - info: wled.0 (22618) Terminated (NO_ERROR): Without reason
  | 2020-12-25 19:43:00.530 - info: wled.0 (22618) [Error catched and send to Sentry, thank you collaborating!] error: State attribute definition missing for + pmt
  | 2020-12-25 19:43:01.008 - info: host.iobroker-deb instance system.adapter.wled.0 terminated with code 0 (NO_ERROR)
  | 2020-12-25 19:43:01.013 - info: host.iobroker-deb Restart adapter system.adapter.wled.0 because enabled
  | 2020-12-25 19:43:31.033 - info: host.iobroker-deb instance system.adapter.wled.0 started with pid 22878
  | 2020-12-25 19:43:32.552 - info: wled.0 (22878) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
  | 2020-12-25 19:43:32.608 - info: wled.0 (22878) starting. Version 0.5.4 in /opt/iobroker/node_modules/iobroker.wled, node: v12.20.0, js-controller: 3.1.6
  | 2020-12-25 19:43:32.646 - info: wled.0 (22878) Try to contact known devices
  | 2020-12-25 19:43:32.646 - info: wled.0 (22878) Try to contact : "Wohnzimmer Schrank" on IP : 192.168.0.193
  | 2020-12-25 19:43:35.994 - info: wled.0 (22878) Device : "Wohnzimmer Schrank" Successfully connected on IP : 192.168.0.193
  | 2020-12-25 19:43:35.994 - info: wled.0 (22878) Try to contact : "Stehlampe" on IP : 192.168.0.192
  | 2020-12-25 19:43:37.602 - info: wled.0 (22878) [Error catched and send to Sentry, thank you collaborating!] error: State attribute definition missing for + u
  | 2020-12-25 19:43:37.605 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
  | 2020-12-25 19:43:37.606 - error: wled.0 (22878) unhandled promise rejection: Cannot read property 'captureException' of undefined
  | 2020-12-25 19:43:37.607 - error: wled.0 (22878) TypeError: Cannot read property 'captureException' of undefined
  | at Wled.sendSentry (/opt/iobroker/node_modules/iobroker.wled/main.js:802:37)
  | at Wled.create_state (/opt/iobroker/node_modules/iobroker.wled/main.js:698:11)
  | at Wled.readData (/opt/iobroker/node_modules/iobroker.wled/main.js:426:18)
  | at runMicrotasks ()
  | at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | at async Wled.tryKnownDevices (/opt/iobroker/node_modules/iobroker.wled/main.js:638:19)
  | at async Wled.onReady (/opt/iobroker/node_modules/iobroker.wled/main.js:49:3)
  | 2020-12-25 19:43:37.609 - info: wled.0 (22878) cleaned everything up...
  | 2020-12-25 19:43:37.628 - info: wled.0 (22878) terminating
  | 2020-12-25 19:43:37.629 - info: wled.0 (22878) Terminated (NO_ERROR): Without reason
  | 2020-12-25 19:43:37.635 - info: wled.0 (22878) [Error catched and send to Sentry, thank you collaborating!] error: State attribute definition missing for + t
  | 2020-12-25 19:43:37.685 - info: wled.0 (22878) [Error catched and send to Sentry, thank you collaborating!] error: State attribute definition missing for + pmt
  | 2020-12-25 19:43:38.164 - info: host.iobroker-deb instance system.adapter.wled.0 terminated with code 0 (NO_ERROR)
  | 2020-12-25 19:43:38.165 - info: host.iobroker-deb Restart adapter system.adapter.wled.0 because enabled


```

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/27df97dcfb65e9024c09e5ed84354af697bbb209
